#!/usr/bin/env python
# Author: Willem Thiart <himself@willemthiart.com>
# Copyright: Willem Thiart 2014

import locale
try:
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline, default_description
import pytestwriter

description = ("Generates test code.  " + default_description)

publish_cmdline(writer=pytestwriter.Writer(), description=description)
